import "./globals.css";
import Footer from "@/UI/footer/Footer";
import Navbar from "@/UI/navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
